INSERT INTO dbo.Users (FirstName, LastName, Login, PasswordHash, CodeHash, BaseSalary, HourlyRate) VALUES ('Robin', 'Hawdon', 'rh1', 'haslorh1', '1', 1.00, 1.00);
INSERT INTO dbo.Users (FirstName, LastName, Login, PasswordHash, CodeHash, BaseSalary, HourlyRate) VALUES ('Elzbieta', 'Wozniak', 'ew1', 'ew1', '1', 1.00, 1.00);
INSERT INTO dbo.Users (FirstName, LastName, Login, PasswordHash, CodeHash, BaseSalary, HourlyRate) VALUES ('Marcin', 'Slawinski', 'ms1', 'ms1', '1', 1.00, 1.00);
INSERT INTO dbo.Users (FirstName, LastName, Login, PasswordHash, CodeHash, BaseSalary, HourlyRate) VALUES ('Andrzej', 'Nejman', 'an1', 'an1', '1', 1.00, 1.00);
INSERT INTO dbo.Users (FirstName, LastName, Login, PasswordHash, CodeHash, BaseSalary, HourlyRate) VALUES ('Wojciech', 'Stefaniak', 'ws1', 'ws1', '1', 1.00, 1.00);
INSERT INTO dbo.Users (FirstName, LastName, Login, PasswordHash, CodeHash, BaseSalary, HourlyRate) VALUES ('Viola', 'Piekut', 'vp1', 'vp1', '1', 1.00, 1.00);
INSERT INTO dbo.Users (FirstName, LastName, Login, PasswordHash, CodeHash, BaseSalary, HourlyRate) VALUES ('Maciej', 'Chojnacki', 'mc1', 'mc1', '1', 1.00, 1.00);
INSERT INTO dbo.Users (FirstName, LastName, Login, PasswordHash, CodeHash, BaseSalary, HourlyRate) VALUES ('Malgorzata', 'Nejman', 'mn1', 'mn1', '1', 1.00, 1.00);
INSERT INTO dbo.Users (FirstName, LastName, Login, PasswordHash, CodeHash, BaseSalary, HourlyRate) VALUES ('Anna', 'Cieslak', 'ac1', 'ac1', '1', 1.00, 1.00);